default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5433
  username: k.ilcenko

development:
  <<: *default
  database: it_blog_development

test:
  <<: *default
  database: it_blog_test

production:
  <<: *default
  database: it_blog_production
  username: it_blog
  password: <%= ENV['IT_BLOG_DATABASE_PASSWORD'] %>